CREATE DATABASE SQLJOINSDB
USE SQLJOINSDB
CREATE TABLE TABLE1 (ID INT NULL)
INSERT INTO TABLE1 VALUES (1),(1),(2),(2),(NULL),(NULL), (3),(4)

CREATE TABLE TABLE2 (ID INT NULL) 
INSERT INTO TABLE2 VALUES (1),(1),(2),(NULL),(5),(6)

SELECT * FROM TABLE1
SELECT * FROM TABLE2

SELECT * FROM TABLE1 TB1 INNER JOIN TABLE2 TB2 ON TB1.ID = TB2.ID -- TOTAL RECORDS -  6
SELECT * FROM TABLE1 TB1 LEFT JOIN TABLE2 TB2 ON TB1.ID = TB2.ID -- TOTAL RECORDS - 8
SELECT * FROM TABLE1 TB1 RIGHT JOIN TABLE2 TB2 ON TB1.ID = TB2.ID -- TOTAL RECORDS - 7
SELECT * FROM TABLE1 TB1 CROSS JOIN TABLE2 TB2 --  TOTAL RECORDS -24
SELECT * FROM TABLE1 TB1 FULL JOIN TABLE2 TB2 ON TB1.ID = TB2.ID -- TOTAL RECORDS - 9

--IF YOU DO NOT WANT TO IGNORE NULL VALUES 
SELECT * FROM TABLE1 TB1 INNER JOIN TABLE2 TB2 ON TB1.ID = TB2.ID OR ISNULL(TB1.ID, 0) = ISNULL(TB2.ID, 0)-- TOTAL RECORDS -  8
-- ONLY RIGHT SIDE TABLE DATA (EXCLUDING LEFT SIDE MATCHING DATA, matching null will also come. if do not want matching null then add "and TB2.ID is not null")
SELECT * FROM TABLE1 TB1 RIGHT JOIN TABLE2 TB2 ON TB1.ID = TB2.ID where  TB1.ID is null-- TOTAL RECORDS -  3
-- ONLY LEFT SIDE TABLE DATA (EXCLUDING RIGHT SIDE MATCHING DATA, matching null will also come. if do not want matching null then add "and TB1.ID is not null")
SELECT * FROM TABLE1 TB1 LEFT JOIN TABLE2 TB2 ON TB1.ID = TB2.ID where TB2.ID is null -- TOTAL RECORDS - 4